#####基础配置   开发环境
settings:
  ## 线程池的初始化 线程数量
  coreThreadPoolNum: 20
spring:
  data:
    mongodb:
      ## 连接mongo数据库
      uri: mongodb://admin:admin@127.0.0.1:27017/lyAdmin
  redis:
    # Redis服务器地址
    host: 127.0.0.1
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接端口
    port: 6379
    password: JDJHSY73MHGNWCBXB6QH9G6JHAN2HQ5YJ278DENCRABEW9EAJYFG4Z4BEMMNTZ5N8HUVXKFHHUJ8U76M4ZS5W9ZG79ZB99VPXCUG
    #连接超时时间（毫秒）
    timeout: 30000ms
    ## springboot 中redis默认使用lettuce, 本系统使用jedis, 如果要用默认的,配置上只需要将jedis换成lettuce即可
    lettuce:
    ## 关闭超时时间
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
      shutdown-timeout: 100ms
#    jedis:
#      pool:
#        # 连接池最大连接数（使用负值表示没有限制）
#        max-active: 8
#        #连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1
#        # 连接池中的最大空闲连接
#        max-idle: 8
#        # 连接池中的最小空闲连接
#        min-idle: 0
server:
  ##开发环境的项目启动端口
  port: 8080
## 日志打印级别
debug: true
